# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c58d3a0a88c0f6447f2be4b7900d4b74865dc765884769287854fb21ebf84281c4f82bded51c8333ecb7be6037f1d742a508bf51bce73a579d34d75ef783b4e

test:
  secret_key_base: 24d2d7bfdf0665057d756ef48f02fda17309d0e620e28192a36d4d4e3980778f82a8ae6593ef767ac481447857613095543a7a62cef0cac59c0f1768702dc9a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
